# Generated by Django 5.0.4 on 2024-04-19 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('vin_number', models.CharField(max_length=17)),
                ('mileage', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=10)),
                ('body_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Liftback', 'Liftback'), ('Kombi', 'Kombi'), ('SUV', 'SUV'), ('Van', 'Van'), ('Cupe', 'Cupe'), ('Roadster', 'Roadster'), ('Cabriolet', 'Cabriolet'), ('Pick-up', 'Pick-up')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('Hybryda PHEV', 'Hybryda PHEV'), ('Hybryda HEV', 'Hybryda HEV'), ('Elektryczny', 'Elektryczny'), ('Wodór', 'Wodór')], max_length=20)),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('engine_power', models.PositiveIntegerField()),
                ('fuel_consumption_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuel_consumption_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuel_consumption_3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('color', models.CharField(max_length=50)),
                ('technical_condition', models.TextField()),
                ('equipment_list', models.TextField()),
                ('seats', models.PositiveIntegerField()),
                ('trunk_space', models.PositiveIntegerField()),
                ('catalog_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('service_interval_km', models.PositiveIntegerField(default=30000)),
                ('service_interval_months', models.PositiveIntegerField(default=12)),
                ('damage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('driver_license_number', models.CharField(max_length=20)),
                ('max_rental_days', models.PositiveIntegerField(default=3)),
                ('is_vip', models.BooleanField(default=False)),
                ('client_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerShipNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Avaiable', 'Dostępny'), ('Service', 'Serwis'), ('Approved', 'Zatwierdzono'), ('Pending', 'Do zatwierdzenia'), ('Buffer', 'Dzień buforowy')], default='Pending', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='DealerShipUser',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cars.client')),
                ('dealer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_user', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.dealershipnetwork')),
            ],
            bases=('cars.client',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cars.client')),
                ('hire_date', models.DateField()),
                ('years_of_service', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=4000, max_digits=10)),
                ('driver_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cars.client',),
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('distance', models.IntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('new_damage', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.client')),
                ('dealership_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_dealership_user', to='cars.dealershipuser')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_driver', to='cars.driver')),
            ],
        ),
        migrations.CreateModel(
            name='FleetManager',
            fields=[
                ('driver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cars.driver')),
                ('fleet_manager_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleetmanager_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cars.driver',),
        ),
    ]
