# Generated by Django 5.0.4 on 2024-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('Approved', 'Zatwierdzono'), ('Buffer', 'Dzień buforowy'), ('Avaiable', 'Dostępny'), ('Service', 'Serwis'), ('Pending', 'Do zatwierdzenia')], default='Pending', max_length=20),
        ),
    ]
