# Generated by Django 5.0.4 on 2024-04-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('Pending', 'Do zatwierdzenia'), ('Approved', 'Zatwierdzono'), ('Avaiable', 'Dostępny'), ('Service', 'Serwis'), ('Buffer', 'Dzień buforowy')], default='Pending', max_length=20),
        ),
    ]
