# Generated by Django 5.0.4 on 2024-04-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('Service', 'Serwis'), ('Avaiable', 'Dostępny'), ('Pending', 'Do zatwierdzenia'), ('Buffer', 'Dzień buforowy'), ('Approved', 'Zatwierdzono')], default='Pending', max_length=20),
        ),
    ]
