# Generated by Django 5.0.4 on 2024-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('Service', 'Serwis'), ('Approved', 'Zatwierdzono'), ('Buffer', 'Dzień buforowy'), ('Avaiable', 'Dostępny'), ('Pending', 'Do zatwierdzenia')], default='Pending', max_length=20),
        ),
    ]
